#!/usr/bin/with-contenv bash
# shellcheck shell=bash

until [[ -e /var/run/dbus/system_bus_socket ]]; do
    sleep 1s
done

# As suggested by iVolt1 
# (background: https://developers.home-assistant.io/blog/2023/04/13/new_limits_for_add_ons/)
ulimit -n 1048576
exec \
    avahi-daemon --no-chroot
