name: Build Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/templates/*"
      - "**/*.values.yaml"
      - "**/values.yaml"
      - "**/Chart.yaml"

env:
  conf_live_branch: main
  conf_ignore_known_labels_containing_versions: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      files: "${{ steps.extract.outputs.files }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changed:
              - "**/Dockerfile"

      - name: Format output
        id: extract
        run: ./.github/scripts/format.sh ${{ steps.filter.outputs.changed_files }}

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    if: ${{ needs.changes.outputs.files != '[]' }}

    outputs:
      changes: "${{ steps.diff.outputs.changes }}"

    needs:
      - changes

    strategy:
      matrix:
        file: ${{ fromJson(needs.changes.outputs.files) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Retrieve version
        id: version
        run: echo ::set-output name=version::$(sed -nr 's/^FROM quay.*:(.*)/\1/p' Dockerfile)

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: alexbabel/${{ matrix.file }},ghcr.io/alexanderbabel/${{ matrix.file }}
          tags: |
            ${{ steps.version.outputs.version }}
            latest

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
