name: Build Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "spilo/**"

env:
  conf_live_branch: main
  conf_ignore_known_labels_containing_versions: true

jobs:
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/checkout@v5
        with:
          repository: zalando/spilo
          path: upstream-spilo

      - name: Apply patch
        run: cd upstream-spilo && git apply ../spilo/spilo.patch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/alexanderbabel/spilo
          tags: |
            4.0-p3
            latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: upstream-spilo/postgres-appliance
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
